name: ronotes
favicon: null
layout_spectrum: 0.12940625729970634
typography_spectrum: 0.20741247572004795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41182333999313414
  lightness: 0.1618931673001498
  saturation: 0.8185889478772879
  rhythmicContrast: 0.19080694275908172
purpose: []
